# SPDX-FileCopyrightText: 2026 Volker Krause <vkrause@kde.org>
# SPDX-License-Identifier: CC0-1.0

name: Convert Air France SSIM to GTFS for Transitous

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - run: |
          curl --user-agent org.transitous.ssim-converter https://www.data.gouv.fr/api/1/datasets/r/240d45de-fcff-42ed-9e97-5e351d032fea > AF-KL-TO-HV-S26-W26.ssim
          python3 ssim2gtfs.py --ssim AF-KL-TO-HV-S26-W26.ssim --out AF-KL-TO-HV-S26-W26.zip

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: AF-KL-TO-HV-S26-W26.zip

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
